/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QueueImport } from './routes/queue'
import { Route as EnqueueImport } from './routes/enqueue'
import { Route as ConfigImport } from './routes/config'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const QueueRoute = QueueImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRoute,
} as any)

const EnqueueRoute = EnqueueImport.update({
  id: '/enqueue',
  path: '/enqueue',
  getParentRoute: () => rootRoute,
} as any)

const ConfigRoute = ConfigImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigImport
      parentRoute: typeof rootRoute
    }
    '/enqueue': {
      id: '/enqueue'
      path: '/enqueue'
      fullPath: '/enqueue'
      preLoaderRoute: typeof EnqueueImport
      parentRoute: typeof rootRoute
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/enqueue': typeof EnqueueRoute
  '/queue': typeof QueueRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/enqueue': typeof EnqueueRoute
  '/queue': typeof QueueRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/enqueue': typeof EnqueueRoute
  '/queue': typeof QueueRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/config' | '/enqueue' | '/queue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/enqueue' | '/queue'
  id: '__root__' | '/' | '/config' | '/enqueue' | '/queue'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  EnqueueRoute: typeof EnqueueRoute
  QueueRoute: typeof QueueRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  EnqueueRoute: EnqueueRoute,
  QueueRoute: QueueRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/config",
        "/enqueue",
        "/queue"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/config": {
      "filePath": "config.tsx"
    },
    "/enqueue": {
      "filePath": "enqueue.tsx"
    },
    "/queue": {
      "filePath": "queue.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
